### ISSUE TITLE
Fatal error: Uncaught exception

### ISSUE THREAD

**Issue by instocky** [gladyshev/rucaptcha-client#7]
привет.
пробую ваш пример .../generic_client.php
ключ для антикапчи беру с сайта https://anti-captcha.com/clients/settings/apisetup

возвращается ошибка
Fatal error: Uncaught exception 'Rucaptcha\Exception\ErrorResponseException' with message 'Использован несуществующий key.' in I:\openserver525\domains\2017.scripts\19week\id421245182\rucaptcha\vendor\gladyshev\rucaptcha-client\src\GenericClient.php:179 Stack trace: #0 I:\openserver525\domains\2017.scripts\19week\id421245182\rucaptcha\vendor\gladyshev\rucaptcha-client\src\GenericClient.php(124): Rucaptcha\GenericClient->sendCaptcha('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', Array) #1 I:\openserver525\domains\2017.scripts\19week\id421245182\rucaptcha\vendor\gladyshev\rucaptcha-client\src\GenericClient.php(113): Rucaptcha\GenericClient->recognize('\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', Array) #2 I:\openserver525\domains\2017.scripts\19week\id421245182\rucaptcha\tmp08.php(22): Rucaptcha\GenericClient->recognizeFile('captcha3950166....') #3 {main} thrown in I:\openserver525\domains\2017.scripts\19week\id421245182\rucaptcha\vendor\gladyshev\rucaptcha-client\src\GenericClient.php on line 179

что посоветуете исправить?

**Comment by gladyshev** [comment]
> что посоветуете исправить?

`$captchaText = (new Anticaptcha('тут ключ'))->recognizeFile(__DIR__ . '/data/captcha.png'); `
У меня все работает. Возможно вы делали так `getenv('ключ')`, скопипастив пример. И да, сорян, что "чуть-чуть" не вовремя, уведомление об ишью затерялось в почте.
